version: '3.7'

services:
  php-apache:
    build:
      context: .
      dockerfile: ./operations/docker/php-apache/Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./docker-compose.env
    ports:
      - 80:80
    user: application
    volumes:
      - ./:/app:cached
      - ./public/cpresources:/app/public/cpresources:delegated
      - ./vendor:/app/vendor:delegated
      - ./storage:/app/storage:delegated
  mysql:
    build:
      context: .
      dockerfile: ./operations/docker/mysql/Dockerfile
    env_file:
      - ./docker-compose.env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
