fieldLayouts:
  0a0b6d87-b8d1-4412-a0d3-acf2ec64fb46:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            style: tip
            tip: "Questions? Email [recipes@onemohrti.me](mailto:recipes@onemohrti.me)\r\n"
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 7d8cc90c-9fdb-474d-8603-838be99bc7a1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Recipe Plugin'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 54ccf5d6-da92-4271-b1f8-57e00e29c2af
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 45ee09d2-45da-47fa-ae52-a4ba7c73b3ab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c054470-464d-4115-b7c8-de5c55df15d5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ecc3a87-e185-4c24-b319-ef3dbbe99592
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Categories
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 43ca756d-4ad2-4e47-937e-962ec8de3f0c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Additional Photos'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 39e5182d-97ef-4d49-ab2f-80fc1f8fef4d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 4
handle: recipes
hasTitleField: false
name: Recipes
section: 8be328ea-62d9-42b7-9b78-07c424cd4724
sortOrder: 1
titleFormat: '{recipe.name}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
