fieldLayouts:
  0a0b6d87-b8d1-4412-a0d3-acf2ec64fb46:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            style: tip
            tip: "1. Add recipe ingredients one-by-one, clicking \"fetch nutrition information\" between each line. It's a longer process, but the API isn't mine aand it's doing a pretty good job.\r\n2. Ratings do not appear on the front end currently, but can still be added.\r\n3. **Total time** will be a range of time, if you enter a total recipe time that doesn't match the prep + cooking time."
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 7d8cc90c-9fdb-474d-8603-838be99bc7a1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Recipe Plugin'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a170c16b-3bd9-4fcc-bb79-a7534dc2558d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Categories
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 43ca756d-4ad2-4e47-937e-962ec8de3f0c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Additional Photos'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 39e5182d-97ef-4d49-ab2f-80fc1f8fef4d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 4
handle: recipes
hasTitleField: false
name: Recipes
section: 8be328ea-62d9-42b7-9b78-07c424cd4724
sortOrder: 1
titleFormat: '{recipe.name}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
