fieldLayouts:
  7e8e7528-1ad0-419a-aac3-f26111093288:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: diet
name: Diet
siteSettings:
  038df939-32f1-4d74-a42e-9c57bdeb55b0:
    hasUrls: true
    template: _sections/recipes/category
    uriFormat: 'diet/{slug}'
structure:
  maxLevels: 1
  uid: f41a5917-a1f5-4b83-a57c-dcfd01162551
