fieldLayouts:
  1ba86fd2-f9a0-497e-9af9-4ee4f2240970:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: ethnicity
name: Ethnicity
siteSettings:
  038df939-32f1-4d74-a42e-9c57bdeb55b0:
    hasUrls: true
    template: _sections/recipes/category
    uriFormat: 'ethnicity/{slug}'
structure:
  maxLevels: 1
  uid: 66d3ccb7-7099-4ebf-83ad-af69daf1622e
