fieldLayouts:
  45e3de76-cf2a-4610-ba02-4afb885f5546:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: liquor
name: Liquor
siteSettings:
  038df939-32f1-4d74-a42e-9c57bdeb55b0:
    hasUrls: true
    template: _sections/drinks/category
    uriFormat: 'liquor/{slug}'
structure:
  maxLevels: 1
  uid: d16747c7-6148-4763-8e27-64eed1bb4489
