contentColumnType: string
fieldGroup: 8e8a3a92-4ae6-4d1c-831f-1ef6db76f546
handle: dish
instructions: ''
name: Dish
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: 'Add Dish'
  showSiteMenu: true
  source: 'group:323c4c22-176b-46b8-8813-32bb56d7f4ad'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
