contentColumnType: text
fieldGroup: ab41c906-bfd1-4292-89fe-04ed83d357bc
handle: featureCategoryHeadline
instructions: ''
name: 'Feature Category Headline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
