contentColumnType: string
fieldGroup: 8e8a3a92-4ae6-4d1c-831f-1ef6db76f546
handle: recipeCategories
instructions: ''
name: 'Recipe Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:b4a63e70-515e-4b32-97b8-2cf6d32448e2'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
