dateModified: 1706023933
email:
  fromEmail: derekmohrdesign@gmail.com
  fromName: Recipes
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0c3e760f-3294-41e0-9911-c57d4c9062bc: General # General
    04e900e4-d729-458d-8a58-aae6caf61e75: 'Recipe Photos' # Recipe Photos
    238d1902-b03f-4df3-8166-39be4347dfcd: 'Site Settings' # Site Settings
    428e5564-9e75-4e1b-a401-af5da8894fa6: 'Drink Photos' # Drink Photos
    9931fe08-b5f7-45bc-9410-2f219f8fd70c: Users # Users
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  kint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      kintDisplayTheme: aante-light.css
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: assets
      publicPath: public
  recipe:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      apiApplicationId: 490c5b08
      apiApplicationKey: 150515764a253f5268876d4297cacb47
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprout-seo:
    edition: lite
    enabled: true
    schemaVersion: 4.5.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Recipes
  retryDuration: null
  schemaVersion: 3.8.0.1
  timeZone: America/Detroit
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: '{username}'
  photoVolumeUid: 9931fe08-b5f7-45bc-9410-2f219f8fd70c # Users
  requireEmailVerification: true
