dateModified: 1617424593
email:
  fromEmail: derekmohrdesign@gmail.com
  fromName: Recipes
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  kint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      kintDisplayTheme: aante-light.css
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: assets
      publicPath: public
  recipe:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      apiApplicationId: 490c5b08
      apiApplicationKey: 150515764a253f5268876d4297cacb47
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprout-seo:
    edition: lite
    enabled: true
    schemaVersion: 4.5.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Recipes
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: America/Detroit
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: '{username}'
  photoVolumeUid: 9931fe08-b5f7-45bc-9410-2f219f8fd70c
  requireEmailVerification: true
