enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  038df939-32f1-4d74-a42e-9c57bdeb55b0:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: about
type: single
