enableVersioning: true
handle: error
name: Error
propagationMethod: all
siteSettings:
  038df939-32f1-4d74-a42e-9c57bdeb55b0:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
